### ISSUE TITLE
4 space instead of tab

### ISSUE THREAD

**Issue by Uveso** [FAForever/fa-total-mayhem#33]
Some files are formatted with tabs at the start instead of 4 spaces per tab.

In 2016, we agreed to use 4 spaces instead of tabs for formatting our files.

I’d like to replace tabs with spaces to maintain consistency. Are there any concerns with making this change?

**Comment by MrRowey** [comment]
ive allways used tab over spaces.

**Comment by Garanas** [comment]
I'm not sure where the tabs originate from. But feel free to convert them to spaces. Spaces are superior anyway 😜 .

**Comment by MrRowey** [comment]
i supose i use tab but have vscode st to spaces.

**Comment by Garanas** [comment]
@Uveso Next time, please using closing key words in the pull request that tackles an issue. See also:

- https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests

That way the issue is linked (that I now did manually) and you can then find the issue/pull request in the `Development` section on the right.

**Comment by Uveso** [comment]
Thanks for the tip! That sounds like a really useful feature—I’ll make sure to use closing keywords in my pull requests next time to link issues directly!
